// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: api/test.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RandomNumberClient is the client API for RandomNumber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomNumberClient interface {
	// Send max number and response random number smaller than max number
	GetRandomNumber(ctx context.Context, in *RandomNumberRequest, opts ...grpc.CallOption) (*RandomNumberReply, error)
}

type randomNumberClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomNumberClient(cc grpc.ClientConnInterface) RandomNumberClient {
	return &randomNumberClient{cc}
}

func (c *randomNumberClient) GetRandomNumber(ctx context.Context, in *RandomNumberRequest, opts ...grpc.CallOption) (*RandomNumberReply, error) {
	out := new(RandomNumberReply)
	err := c.cc.Invoke(ctx, "/RandomNumber/GetRandomNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomNumberServer is the server API for RandomNumber service.
// All implementations must embed UnimplementedRandomNumberServer
// for forward compatibility
type RandomNumberServer interface {
	// Send max number and response random number smaller than max number
	GetRandomNumber(context.Context, *RandomNumberRequest) (*RandomNumberReply, error)
	mustEmbedUnimplementedRandomNumberServer()
}

// UnimplementedRandomNumberServer must be embedded to have forward compatible implementations.
type UnimplementedRandomNumberServer struct {
}

func (UnimplementedRandomNumberServer) GetRandomNumber(context.Context, *RandomNumberRequest) (*RandomNumberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomNumber not implemented")
}
func (UnimplementedRandomNumberServer) mustEmbedUnimplementedRandomNumberServer() {}

// UnsafeRandomNumberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomNumberServer will
// result in compilation errors.
type UnsafeRandomNumberServer interface {
	mustEmbedUnimplementedRandomNumberServer()
}

func RegisterRandomNumberServer(s grpc.ServiceRegistrar, srv RandomNumberServer) {
	s.RegisterService(&RandomNumber_ServiceDesc, srv)
}

func _RandomNumber_GetRandomNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomNumberServer).GetRandomNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RandomNumber/GetRandomNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomNumberServer).GetRandomNumber(ctx, req.(*RandomNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomNumber_ServiceDesc is the grpc.ServiceDesc for RandomNumber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomNumber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RandomNumber",
	HandlerType: (*RandomNumberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomNumber",
			Handler:    _RandomNumber_GetRandomNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/test.proto",
}
